In [2]:
from tensorflow.keras.preprocessing.text import one_hot # type: ignore

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocubulary size
voc_size = 10000

In [7]:
one_hot_repr = [one_hot(words , voc_size)for words in sent]
one_hot_repr

[[9928, 7196, 4443, 2703],
 [9928, 7196, 4443, 3290],
 [9928, 9796, 4443, 2371],
 [4506, 1758, 7422, 8101, 5410],
 [4506, 1758, 7422, 8101, 2391],
 [7293, 9928, 4060, 4443, 1656],
 [6684, 1548, 7907, 8101]]

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
import numpy as np
from tensorflow.keras.models import Sequential

In [10]:
sent_size = 8

In [15]:
embedding_docs = pad_sequences(one_hot_repr , padding = 'pre' , maxlen = sent_size)

In [16]:
embedding_docs

array([[   0,    0,    0,    0, 9928, 7196, 4443, 2703],
       [   0,    0,    0,    0, 9928, 7196, 4443, 3290],
       [   0,    0,    0,    0, 9928, 9796, 4443, 2371],
       [   0,    0,    0, 4506, 1758, 7422, 8101, 5410],
       [   0,    0,    0, 4506, 1758, 7422, 8101, 2391],
       [   0,    0,    0, 7293, 9928, 4060, 4443, 1656],
       [   0,    0,    0,    0, 6684, 1548, 7907, 8101]])

In [17]:
## Feature Representation
dim = 10 ## How many Features

In [18]:
model = Sequential()
model.add(Embedding(voc_size , dim , input_length = sent_size))
model.compile('adam' , 'mse')

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [20]:
## Convert to Vectors Each word is having 10 features

model.predict(embedding_docs)

1/1 [==============================] - 0s 205ms/step


array([[[ 2.44039930e-02,  2.40223482e-03, -3.60810272e-02,
         -1.90653335e-02,  2.85934918e-02, -3.83753292e-02,
          2.52758376e-02,  4.31136228e-02,  1.97104923e-02,
          9.03262943e-03],
        [ 2.44039930e-02,  2.40223482e-03, -3.60810272e-02,
         -1.90653335e-02,  2.85934918e-02, -3.83753292e-02,
          2.52758376e-02,  4.31136228e-02,  1.97104923e-02,
          9.03262943e-03],
        [ 2.44039930e-02,  2.40223482e-03, -3.60810272e-02,
         -1.90653335e-02,  2.85934918e-02, -3.83753292e-02,
          2.52758376e-02,  4.31136228e-02,  1.97104923e-02,
          9.03262943e-03],
        [ 2.44039930e-02,  2.40223482e-03, -3.60810272e-02,
         -1.90653335e-02,  2.85934918e-02, -3.83753292e-02,
          2.52758376e-02,  4.31136228e-02,  1.97104923e-02,
          9.03262943e-03],
        [ 6.82765245e-03, -1.87904481e-02, -2.12841518e-02,
         -3.80366668e-02, -1.58246867e-02,  1.55860223e-02,
         -2.74916738e-03,  4.39320467e-02, -3.809330

In [ ]:
## First Sentence
model.predict(embedding_docs[0])

1/1 [==============================] - 0s 27ms/step


array([[ 0.02440399,  0.00240223, -0.03608103, -0.01906533,  0.02859349,
        -0.03837533,  0.02527584,  0.04311362,  0.01971049,  0.00903263],
       [ 0.02440399,  0.00240223, -0.03608103, -0.01906533,  0.02859349,
        -0.03837533,  0.02527584,  0.04311362,  0.01971049,  0.00903263],
       [ 0.02440399,  0.00240223, -0.03608103, -0.01906533,  0.02859349,
        -0.03837533,  0.02527584,  0.04311362,  0.01971049,  0.00903263],
       [ 0.02440399,  0.00240223, -0.03608103, -0.01906533,  0.02859349,
        -0.03837533,  0.02527584,  0.04311362,  0.01971049,  0.00903263],
       [ 0.00682765, -0.01879045, -0.02128415, -0.03803667, -0.01582469,
         0.01558602, -0.00274917,  0.04393205, -0.03809331,  0.03920523],
       [ 0.03547073,  0.04321284,  0.01462945, -0.02335124,  0.00836279,
        -0.00662643,  0.03268397,  0.04330866,  0.04093207,  0.00142697],
       [-0.04910081, -0.02036985, -0.02417706,  0.04555443, -0.02763894,
        -0.02410978,  0.0115086 ,  0.04220903